### ISSUE TITLE
Spell lists are wonky in a few places

### ISSUE THREAD

**Issue by nikjft** [vidalvanbergen/FightClub5eXML#16]
It looks like some of the spell lists are incorrect for sub-classes. Found missing spells in a number of cleric domains, the Eberron dragonmarks, and in some Warlock subclasses. Didn't do a full audit. 

I might just fix it myself if I have time, but it looked like you were doing some clean up of cleric domains, so it might all be fresh in your head.

**Comment by vidalvanbergen** [comment]
Fixed spell "Commune With City (UA)" being the wrong level.

Humblewood Campaign Setting - Cleric Circle Domain:
Heroism is a 1st level spell, but the book gives it to you at 3rd cleric level.

Removed Cleric (Nature) From "Call a Roggenwolf".

Removed Cleric (Peace) from "Acid Splash (UA)".

Added wyrm colors to "Warlock (Ancient Wyrm (HB))".

Fixed "Warlock (Great Dreamer (HB))" typo from "Conjure Minor Elementals".

Removed "Warlock (Lurker in the Deep (UA))" from the "Shatter" spell.

Fixed "Mages of Witherbloom" Spell lists accidentally using "Mass Cure Wounds" instead of "Death Ward".

Removed "Ray of Sickness", "Silence", "Feign Death", "Aura of Life", "Contagion", and "Legend Lore" from "Warlock (Undead (UA))" spell list.

Added "(HB)" tag to my own "Ungodly SCIENCE!" Spell list.

That should be all the Cleric and Warlock spell lists fixed.
